### ISSUE TITLE
hi, how to compressing resources ( gzip ) with dietjs?

### ISSUE THREAD

**Issue by wlekin** [adamhalasz/diet#28]
*Actually this is not a issue.
Hi, dietjs is one of the best web framework of nodejs, and I have a web project up and running which use dietjs and nedb, everything working great as expected.
However, [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights) asked me to compressing resources to reduce their transfer size. I googled around and was unable to find any sample or hint about dietjs and gzip/zlib ( everyone just talking about expressjs), I have no idea how to respond the gunzip. Can you kindly give us a sample? Thanks!

**Comment by adamhalasz** [comment]
Hi @wlekin thanks a lot! 

Can you send me the PageSpeed Report so I can see the details of your issue.

If you are using diet-static to serve static resource then CSS and Javascript files are already compressed. You probably get the message because your HTML or other resource types are not compressed. If HTML is the case then that'a a problem with the HTML Template Engine.

Compression should happen in a Footer Middleware. Here is the Node.js Zlib implementation in diet-static for CSS and JS Files. Feel free to fork it :) https://github.com/adamhalasz/diet-static/blob/master/index.js#L35

And here is the Zlib module:
https://nodejs.org/api/zlib.html

Here is a simplistic (untested) example to give you an idea how to implement such a Footer Middleware.
```
var path = require('path')

app.footer(function($){
    var extension = path.extname($.url.pathname)
    if(extension){
         fs.readFile(source, function(readError, data){
            if(readError) throw readError
            var buffer = new Buffer(data)
            
            zlib.gzip(buffer, function(error, gzippedData){
                if(error) throw error
                
                $.header('Content-Encoding', 'gzip')
                $.header('Vary', 'Accept-Encoding')
                
                $.end(gzippedData)
            })
         })
    }
})
```

Let me know if you have any further questions.

Thanks,
Adam

P.S. A few updates are on the way regarding HTML Templates and Static Resources in the next couple weeks.

**Comment by wlekin** [comment]
It look simpler than I think, I will certainly give it a try and look forward to the next update.
Thank @adamhalasz

**Comment by wlekin** [comment]
I try to implement compress html as a Footer but no success.
So, to work around with it, I modified diet-ect to enable html compressionm.
Replace line 27: 
from:

    $.response.end(html)
to:

    $.response.end( require( 'zlib' ).gzipSync( new Buffer( html ) ) );

**Comment by adamhalasz** [comment]
As you fixed this for yourself I will close this for now and maybe open it if there are new updates around this topic.
